spring.application.name=Portal

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool

# ===============================
# LOGGING (SQL + DEBUG)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# JACKSON (JSON FORMAT)
# ===============================
spring.jackson.serialization.fail-on-empty-beans=false

# ===============================
# FILE UPLOAD (OPTIONAL FUTURE USE)
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
