spring.application.name=portal

# Default config (safe)
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.properties.hibernate.dialect=

# Activate local profile
spring.profiles.active=local